# Generated by Django 5.2.17 on 2026-09-13 07:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(editable=False, max_length=12, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=80)),
                ('zip_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='United States', max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('roasting', 'Queued for roasting'), ('shipped', 'Shipped')], default='received', max_length=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('shipping', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.SlugField(db_comment='Storefront id, e.g. cloud-forest', unique=True)),
                ('name', models.CharField(max_length=80)),
                ('origin', models.CharField(max_length=80)),
                ('region', models.CharField(max_length=120)),
                ('roast', models.CharField(choices=[('light', 'Light roast'), ('medium', 'Medium roast'), ('dark', 'Dark roast'), ('decaf', 'Decaf')], db_comment='Storefront category', max_length=8)),
                ('process', models.CharField(max_length=120)),
                ('varietal', models.CharField(max_length=120)),
                ('altitude', models.CharField(max_length=60)),
                ('notes', models.JSONField(db_comment='Three tasting notes, in cupping order', default=list)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('weight', models.CharField(default='250 g', max_length=20)),
                ('roast_level', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('cup_score', models.DecimalField(decimal_places=1, max_digits=4)),
                ('badge', models.CharField(blank=True, max_length=60)),
                ('description', models.TextField()),
                ('story', models.TextField()),
                ('image', models.URLField(max_length=500)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'sku'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('pk', models.CompositePrimaryKey('order', 'product', 'grind', blank=True, editable=False, primary_key=True, serialize=False)),
                ('grind', models.CharField(choices=[('Whole bean', 'Whole bean'), ('Filter', 'Filter'), ('Espresso', 'Espresso')], max_length=12)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('unit_price', models.DecimalField(db_comment='Price snapshot at purchase', decimal_places=2, max_digits=6)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='shop.product')),
            ],
        ),
    ]
